// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzN0Y3Tk-wT5D88DoFvBLdn2pj43gUME',
    appId: '1:408911087335:web:ae6b9e2bc4016afc28c442',
    messagingSenderId: '408911087335',
    projectId: 'blogapp-12205',
    authDomain: 'blogapp-12205.firebaseapp.com',
    storageBucket: 'blogapp-12205.appspot.com',
    measurementId: 'G-WR2QXDNQ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTAX6Cnz7lKIpFQCP-SqJjx6_mCKoQ_lw',
    appId: '1:408911087335:android:30e0cf02a329f5ea28c442',
    messagingSenderId: '408911087335',
    projectId: 'blogapp-12205',
    storageBucket: 'blogapp-12205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQneOyPInBp1IUN4YfatB2ASQ_kTdtBN0',
    appId: '1:408911087335:ios:f273895a3c0cb21628c442',
    messagingSenderId: '408911087335',
    projectId: 'blogapp-12205',
    storageBucket: 'blogapp-12205.appspot.com',
    iosBundleId: 'com.example.projectdraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQneOyPInBp1IUN4YfatB2ASQ_kTdtBN0',
    appId: '1:408911087335:ios:d71460182c33275b28c442',
    messagingSenderId: '408911087335',
    projectId: 'blogapp-12205',
    storageBucket: 'blogapp-12205.appspot.com',
    iosBundleId: 'com.example.projectdraft.RunnerTests',
  );
}
